language: php

php:
  - 5.1
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --configuration phpunit.xml --coverage-text